import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Forms",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="pt-br">
      <body className="bg-blue-500 w-full h-screen flex justify-center items-center">
        {children}
      </body>
    </html>
  );
}
